services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0
    ports:
      - 8085:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/
